export const sampleProjects = [
    {
        id: "1",
        name: "E-commerce Platform",
        date: "2 hours ago",
        status: "completed",
        description: "Modern e-commerce platform with AI-powered recommendations",
        architecture: [
            {
                title: "Frontend Application",
                description: "Next.js storefront with dynamic product pages and cart",
                technologies: ["Next.js 16", "React", "Tailwind CSS", "Stripe.js"],
                category: "frontend",
                details: [
                    "Server components for product listings",
                    "Client-side cart with optimistic updates",
                    "Image optimization with blur placeholders",
                ],
            },
            {
                title: "Backend Services",
                description: "Node.js API with order management and inventory",
                technologies: ["Node.js", "Express", "Redis", "Bull Queue"],
                category: "backend",
                details: [
                    "Order processing with queue system",
                    "Inventory management with real-time sync",
                    "Webhook handlers for payment events",
                ],
            },
            {
                title: "AI Recommendations",
                description: "Personalized product suggestions using ML models",
                technologies: ["Python", "TensorFlow", "OpenAI API", "FastAPI"],
                category: "ai",
                details: [
                    "Collaborative filtering for recommendations",
                    "Natural language product search",
                    "Dynamic pricing suggestions",
                ],
            },
            {
                title: "Data Storage",
                description: "PostgreSQL for products, Redis for sessions and cache",
                technologies: ["PostgreSQL", "Redis", "Prisma", "S3"],
                category: "database",
                details: [
                    "Product catalog with variants support",
                    "Order history with full audit trail",
                    "Media storage for product images",
                ],
            },
            {
                title: "Payment Gateway",
                description: "Stripe integration with subscription support",
                technologies: ["Stripe", "REST API", "Webhooks", "JWT"],
                category: "api",
                details: [
                    "Checkout sessions with 3D Secure",
                    "Subscription management",
                    "Refund and dispute handling",
                ],
            },
            {
                title: "Cloud Infrastructure",
                description: "Vercel deployment with edge functions",
                technologies: ["Vercel", "AWS Lambda", "CloudFront", "Docker"],
                category: "infrastructure",
                details: [
                    "Edge-optimized product pages",
                    "Auto-scaling for flash sales",
                    "Multi-region deployment",
                ],
            },
        ],
    },
    {
        id: "2",
        name: "Social Media App",
        date: "Yesterday",
        status: "in-progress",
        description: "Real-time social platform with stories and messaging",
        architecture: [
            {
                title: "Frontend Application",
                description: "React Native mobile app with web companion",
                technologies: ["React Native", "Expo", "Next.js", "Reanimated"],
                category: "frontend",
                details: [
                    "Infinite scroll feeds with virtualization",
                    "Story viewer with gesture controls",
                    "Push notifications integration",
                ],
            },
            {
                title: "Backend Services",
                description: "GraphQL API with real-time subscriptions",
                technologies: ["Node.js", "Apollo Server", "Socket.io", "Redis Pub/Sub"],
                category: "backend",
                details: [
                    "GraphQL subscriptions for live updates",
                    "Fan-out messaging system",
                    "Content moderation pipeline",
                ],
            },
            {
                title: "AI Content Moderation",
                description: "Automated content filtering and safety checks",
                technologies: ["OpenAI Moderation", "AWS Rekognition", "Python", "Celery"],
                category: "ai",
                details: [
                    "Image and video content screening",
                    "Text toxicity detection",
                    "Spam and bot detection",
                ],
            },
            {
                title: "Data Storage",
                description: "Graph database for social connections",
                technologies: ["Neo4j", "PostgreSQL", "Redis", "Cloudinary"],
                category: "database",
                details: [
                    "Graph queries for friend suggestions",
                    "Time-series data for analytics",
                    "CDN-backed media storage",
                ],
            },
            {
                title: "API Layer",
                description: "GraphQL with REST fallback for integrations",
                technologies: ["GraphQL", "REST", "OAuth 2.0", "WebSocket"],
                category: "api",
                details: [
                    "Persisted queries for performance",
                    "Rate limiting per user tier",
                    "Third-party app integration",
                ],
            },
            {
                title: "Cloud Infrastructure",
                description: "Multi-region deployment for low latency",
                technologies: ["AWS", "Kubernetes", "Terraform", "DataDog"],
                category: "infrastructure",
                details: [
                    "Global CDN for media delivery",
                    "Auto-scaling based on activity",
                    "Real-time monitoring and alerts",
                ],
            },
        ],
    },
    {
        id: "3",
        name: "AI Chatbot System",
        date: "3 days ago",
        status: "completed",
        description: "Enterprise chatbot with knowledge base integration",
        architecture: [
            {
                title: "Frontend Application",
                description: "Embeddable chat widget and admin dashboard",
                technologies: ["React", "Tailwind CSS", "Framer Motion", "Web Components"],
                category: "frontend",
                details: [
                    "Lightweight embeddable widget (< 50KB)",
                    "Real-time typing indicators",
                    "File upload and preview",
                ],
            },
            {
                title: "Backend Services",
                description: "Conversation orchestration with context management",
                technologies: ["Node.js", "FastAPI", "Redis", "WebSocket"],
                category: "backend",
                details: [
                    "Multi-turn conversation handling",
                    "Session persistence across devices",
                    "Handoff to human agents",
                ],
            },
            {
                title: "AI Language Model",
                description: "RAG-powered responses with custom knowledge",
                technologies: ["OpenAI GPT-4", "LangChain", "Pinecone", "Python"],
                category: "ai",
                details: [
                    "Retrieval augmented generation",
                    "Custom fine-tuned embeddings",
                    "Intent classification and routing",
                ],
            },
            {
                title: "Data Storage",
                description: "Vector database for semantic search",
                technologies: ["Pinecone", "PostgreSQL", "Redis", "S3"],
                category: "database",
                details: [
                    "Document chunking and indexing",
                    "Conversation history storage",
                    "Analytics data warehouse",
                ],
            },
            {
                title: "Integration API",
                description: "Webhooks and REST API for CRM integration",
                technologies: ["REST", "Webhooks", "OAuth 2.0", "gRPC"],
                category: "api",
                details: [
                    "Salesforce and HubSpot connectors",
                    "Custom webhook events",
                    "Bulk data import/export",
                ],
            },
            {
                title: "Cloud Infrastructure",
                description: "Serverless deployment with GPU access",
                technologies: ["AWS Lambda", "Modal", "Docker", "CloudWatch"],
                category: "infrastructure",
                details: [
                    "On-demand GPU for embeddings",
                    "Cold start optimization",
                    "Cost monitoring and alerts",
                ],
            },
        ],
    },
    {
        id: "4",
        name: "Healthcare Dashboard",
        date: "1 week ago",
        status: "draft",
        description: "Patient monitoring dashboard with HIPAA compliance",
        architecture: [
            {
                title: "Frontend Application",
                description: "Real-time monitoring dashboard with alerts",
                technologies: ["Next.js", "D3.js", "Tailwind CSS", "React Query"],
                category: "frontend",
                details: [
                    "Real-time vital signs charts",
                    "Alert notification system",
                    "Accessible design (WCAG 2.1 AA)",
                ],
            },
            {
                title: "Backend Services",
                description: "HIPAA-compliant API with audit logging",
                technologies: ["Node.js", "Express", "Winston", "Joi"],
                category: "backend",
                details: [
                    "Complete audit trail logging",
                    "Role-based access control",
                    "Data encryption at rest and transit",
                ],
            },
            {
                title: "AI Diagnostics",
                description: "ML models for anomaly detection in vitals",
                technologies: ["Python", "scikit-learn", "TensorFlow", "MLflow"],
                category: "ai",
                details: [
                    "Anomaly detection in vital signs",
                    "Predictive risk scoring",
                    "Explainable AI for clinicians",
                ],
            },
            {
                title: "Data Storage",
                description: "HIPAA-compliant PostgreSQL with encryption",
                technologies: ["PostgreSQL", "TimescaleDB", "Redis", "AWS KMS"],
                category: "database",
                details: [
                    "Time-series data for vitals",
                    "Encrypted patient records",
                    "Automated backup and recovery",
                ],
            },
            {
                title: "HL7 FHIR API",
                description: "Healthcare interoperability standards",
                technologies: ["FHIR R4", "REST", "OAuth 2.0", "SMART on FHIR"],
                category: "api",
                details: [
                    "FHIR resource endpoints",
                    "EHR system integration",
                    "Patient consent management",
                ],
            },
            {
                title: "Cloud Infrastructure",
                description: "HIPAA-eligible AWS deployment",
                technologies: ["AWS GovCloud", "ECS", "ALB", "CloudTrail"],
                category: "infrastructure",
                details: [
                    "HIPAA BAA compliance",
                    "Network isolation with VPC",
                    "Disaster recovery setup",
                ],
            },
        ],
    },
    {
        id: "5",
        name: "Fintech API",
        date: "2 weeks ago",
        status: "completed",
        description: "Banking API with real-time payments and fraud detection",
        architecture: [
            {
                title: "Frontend Application",
                description: "Developer portal with API documentation",
                technologies: ["Next.js", "MDX", "Tailwind CSS", "Shiki"],
                category: "frontend",
                details: [
                    "Interactive API explorer",
                    "Code samples in multiple languages",
                    "Webhook testing playground",
                ],
            },
            {
                title: "Backend Services",
                description: "High-throughput payment processing engine",
                technologies: ["Go", "gRPC", "Kafka", "Redis"],
                category: "backend",
                details: [
                    "Idempotent payment processing",
                    "Event sourcing for transactions",
                    "Circuit breaker patterns",
                ],
            },
            {
                title: "AI Fraud Detection",
                description: "Real-time transaction risk scoring",
                technologies: ["Python", "XGBoost", "Kafka Streams", "Feature Store"],
                category: "ai",
                details: [
                    "Real-time fraud scoring (< 100ms)",
                    "Behavioral biometrics analysis",
                    "Adaptive rules engine",
                ],
            },
            {
                title: "Data Storage",
                description: "ACID-compliant database with ledger",
                technologies: ["PostgreSQL", "CockroachDB", "Redis", "TimescaleDB"],
                category: "database",
                details: [
                    "Double-entry accounting ledger",
                    "Multi-currency support",
                    "Audit-ready reporting",
                ],
            },
            {
                title: "Payment API",
                description: "PCI-DSS compliant REST and gRPC API",
                technologies: ["REST", "gRPC", "OAuth 2.0", "mTLS"],
                category: "api",
                details: [
                    "ACH and wire transfer support",
                    "Card tokenization vault",
                    "Real-time balance updates",
                ],
            },
            {
                title: "Cloud Infrastructure",
                description: "PCI-compliant multi-region deployment",
                technologies: ["AWS", "Kubernetes", "Vault", "Consul"],
                category: "infrastructure",
                details: [
                    "PCI-DSS Level 1 compliance",
                    "Zero-downtime deployments",
                    "Secrets rotation automation",
                ],
            },
        ],
    },
]

export const defaultArchitecture = [
    {
        title: "Frontend Application",
        description: "Modern React-based UI with real-time collaboration features",
        technologies: ["Next.js 16", "JavaScript", "Tailwind CSS", "Socket.io Client"],
        category: "frontend",
        details: [
            "Server-side rendering for optimal performance",
            "Real-time canvas rendering using Canvas API",
            "Optimistic UI updates for seamless collaboration",
        ],
    },
    {
        title: "Backend Services",
        description: "Scalable Node.js backend with microservices architecture",
        technologies: ["Node.js", "Express", "Redis", "WebSocket"],
        category: "backend",
        details: [
            "Event-driven architecture for real-time sync",
            "Horizontal scaling with load balancing",
            "Rate limiting and request validation",
        ],
    },
    {
        title: "AI Processing Layer",
        description: "Shape recognition and intelligent suggestions powered by ML",
        technologies: ["TensorFlow.js", "OpenAI API", "Python", "FastAPI"],
        category: "ai",
        details: [
            "Real-time shape detection and classification",
            "Smart auto-complete for drawings",
            "Natural language to diagram conversion",
        ],
    },
    {
        title: "Data Storage",
        description: "Multi-layer storage solution for documents and real-time state",
        technologies: ["PostgreSQL", "Redis", "S3", "Prisma"],
        category: "database",
        details: [
            "Document versioning with conflict resolution",
            "Real-time state synchronization",
            "Optimized blob storage for exports",
        ],
    },
    {
        title: "API Gateway",
        description: "Unified API layer with authentication and rate limiting",
        technologies: ["GraphQL", "REST", "JWT", "OAuth 2.0"],
        category: "api",
        details: [
            "Unified GraphQL endpoint for frontend",
            "REST webhooks for third-party integrations",
            "Fine-grained access control",
        ],
    },
    {
        title: "Cloud Infrastructure",
        description: "Containerized deployment with auto-scaling capabilities",
        technologies: ["Vercel", "AWS", "Docker", "Terraform"],
        category: "infrastructure",
        details: [
            "Edge deployment for global low latency",
            "Auto-scaling based on active users",
            "Infrastructure as code for reproducibility",
        ],
    },
]
